# Validate with:
# cat codecov.yml | curl --data-binary @- https://codecov.io/validate

comment:
  # this posts no PR comment if there are no coverage changes
  require_changes: true

ignore:
  - "**/*.g.dart"
  - "maplibre/lib/src/platform/android/jni/**"
  - "example/**"
  - "maplibre_ios/**"

github_checks:
  annotations: false

coverage:
  status:
    project: off
    patch: off