# Validate with:
# cat codecov.yml | curl --data-binary @- https://codecov.io/validate

comment:
  # this posts no PR comment if there are no coverage changes
  require_changes: true

ignore:
  - "**/*.g.dart"
  - "lib/src/platform/android/jni/**"
  - "example/**"

github_checks:
  annotations: false

coverage:
  status:
    project:
      # default is the status check's name, not default settings
      default:
        target: 0
        threshold: 0
