include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 80

analyzer:
  exclude:
    - lib/**.g.dart

linter:
  rules:
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    cascade_invocations: false
    document_ignores: false
    avoid_catches_without_on_clauses: false
    require_trailing_commas: false