import 'package:flutter/painting.dart';
import 'package:maplibre_ios/src/map_state.dart';
import 'package:maplibre_ios/src/offline_manager.dart';
import 'package:maplibre_ios/src/permission_manager.dart';
import 'package:maplibre_ios/src/style/layers/style_layer.dart';
import 'package:maplibre_platform_interface/maplibre_platform_interface.dart';

/// iOS implementation of the federated MapLibre plugin.
final class MapLibrePlugin extends MapLibrePlatform {
  /// This static method registers [MapLibrePlugin] when running on iOS.
  static void registerWith() => MapLibrePlatform.instance = MapLibrePlugin();

  @override
  MapLibreMapState createWidgetState() => MapLibreMapStateIos();

  @override
  Future<OfflineManager> createOfflineManager() =>
      OfflineManagerIos.createInstance();

  @override
  PermissionManager createPermissionManager() => const PermissionManagerIos();

  @override
  bool get offlineManagerIsSupported => true;

  @override
  bool get permissionManagerIsSupported => false;

  @override
  bool get userLocationIsSupported => true;

  /// Create a platform specific [BackgroundStyleLayer] object.
  @override
  BackgroundStyleLayer createBackgroundStyleLayer({
    required String id,
    required bool visible,
    required PropertyValue<Color> color,
    required PropertyValue<String>? pattern,
    required PropertyValue<double> opacity,
    required double minZoom,
    required double maxZoom,
  }) => BackgroundStyleLayerIos(
    id: id,
    visible: visible,
    color: color,
    pattern: pattern,
    opacity: opacity,
    minZoom: minZoom,
    maxZoom: maxZoom,
  );

  /// Create a platform specific [CircleStyleLayer] object.
  @override
  CircleStyleLayer createCircleStyleLayer({
    required String id,
    required String sourceId,
    required String? sourceLayerId,
    required Expression? filter,
    required bool visible,
    required double minZoom,
    required double maxZoom,
    required PropertyValue<Offset> translate,
    required PropertyValue<ReferenceSpace> translateAnchor,
    required PropertyValue<double>? sortKey,
    required PropertyValue<double> radius,
    required PropertyValue<Color> color,
    required PropertyValue<double> blur,
    required PropertyValue<double> opacity,
    required PropertyValue<ReferenceSpace> pitchScale,
    required PropertyValue<ReferenceSpace> pitchAlignment,
    required PropertyValue<double> strokeWidth,
    required PropertyValue<Color> strokeColor,
    required PropertyValue<double> strokeOpacity,
  }) => CircleStyleLayerIos(
    id: id,
    sourceId: sourceId,
    sourceLayerId: sourceLayerId,
    filter: filter,
    visible: visible,
    minZoom: minZoom,
    maxZoom: maxZoom,
    translate: translate,
    translateAnchor: translateAnchor,
    sortKey: sortKey,
    radius: radius,
    color: color,
    blur: blur,
    opacity: opacity,
    pitchScale: pitchScale,
    pitchAlignment: pitchAlignment,
    strokeWidth: strokeWidth,
    strokeColor: strokeColor,
    strokeOpacity: strokeOpacity,
  );

  /// Create a platform specific [ColorReliefStyleLayer] object.
  @override
  ColorReliefStyleLayer createColorReliefStyleLayer({
    required String id,
    required String sourceId,
    required bool visible,
    required PropertyValue<Color>? color,
    required PropertyValue<double> opacity,
    required double minZoom,
    required double maxZoom,
  }) => throw UnsupportedError(
    'ColorReliefStyleLayer is not supported on this platform.',
  );

  /// Create a platform specific [FillExtrusionStyleLayer] object.
  @override
  FillExtrusionStyleLayer createFillExtrusionStyleLayer({
    required String id,
    required String sourceId,
    required double minZoom,
    required double maxZoom,
    required bool visible,
    required Expression? filter,
    required String? sourceLayerId,
    required PropertyValue<double> opacity,
    required PropertyValue<Color> color,
    required PropertyValue<String>? pattern,
    required PropertyValue<double> height,
    required PropertyValue<double> base,
    required PropertyValue<bool> verticalGradient,
    required PropertyValue<Offset> translate,
    required PropertyValue<ReferenceSpace> translateAnchor,
  }) => FillExtrusionStyleLayerIos(
    id: id,
    sourceId: sourceId,
    minZoom: minZoom,
    maxZoom: maxZoom,
    visible: visible,
    filter: filter,
    sourceLayerId: sourceLayerId,
    opacity: opacity,
    color: color,
    pattern: pattern,
    height: height,
    base: base,
    verticalGradient: verticalGradient,
    translate: translate,
    translateAnchor: translateAnchor,
  );

  /// Create a platform specific [FillStyleLayer] object.
  @override
  FillStyleLayer createFillStyleLayer({
    required String id,
    required String sourceId,
    required bool visible,
    required double minZoom,
    required double maxZoom,
    required String? sourceLayerId,
    required Expression? filter,
    required PropertyValue<double>? sortKey,
    required PropertyValue<Offset> translate,
    required PropertyValue<ReferenceSpace> translateAnchor,
    required PropertyValue<bool> antialias,
    required PropertyValue<Color> color,
    required PropertyValue<double> opacity,
    required PropertyValue<Color> outlineColor,
    required PropertyValue<String>? pattern,
  }) => FillStyleLayerIos(
    id: id,
    sourceId: sourceId,
    visible: visible,
    minZoom: minZoom,
    maxZoom: maxZoom,
    sourceLayerId: sourceLayerId,
    filter: filter,
    sortKey: sortKey,
    translate: translate,
    translateAnchor: translateAnchor,
    antialias: antialias,
    color: color,
    opacity: opacity,
    outlineColor: outlineColor,
    pattern: pattern,
  );

  /// Create a platform specific [HeatmapStyleLayer] object.
  @override
  HeatmapStyleLayer createHeatmapStyleLayer({
    required String id,
    required String sourceId,
    required String? sourceLayerId,
    required Expression? filter,
    required bool visible,
    required double minZoom,
    required double maxZoom,
    required PropertyValue<double> radius,
    required PropertyValue<double> weight,
    required PropertyValue<double> intensity,
    required PropertyValue<Color>? color,
    required PropertyValue<double> opacity,
  }) => HeatmapStyleLayerIos(
    id: id,
    sourceId: sourceId,
    sourceLayerId: sourceLayerId,
    filter: filter,
    visible: visible,
    minZoom: minZoom,
    maxZoom: maxZoom,
    radius: radius,
    weight: weight,
    intensity: intensity,
    color: color,
    opacity: opacity,
  );

  /// Create a platform specific [HillshadeStyleLayer] object.
  @override
  HillshadeStyleLayer createHillshadeStyleLayer({
    required String id,
    required String sourceId,
    required bool visible,
    required double minZoom,
    required double maxZoom,
    required PropertyValue<NumberArray> illuminationDirection,
    required PropertyValue<NumberArray> illuminationAltitude,
    required PropertyValue<IlluminationAnchor> illuminationAnchor,
    required PropertyValue<double> exaggeration,
    required PropertyValue<List<Color>> shadowColor,
    required PropertyValue<List<Color>> highlightColor,
    required PropertyValue<Color> accentColor,
    required PropertyValue<HillshadeMethod> method,
  }) => HillshadeStyleLayerIos(
    id: id,
    sourceId: sourceId,
    visible: visible,
    minZoom: minZoom,
    maxZoom: maxZoom,
    illuminationDirection: illuminationDirection,
    // illuminationAltitude: illuminationAltitude,
    illuminationAnchor: illuminationAnchor,
    exaggeration: exaggeration,
    shadowColor: shadowColor,
    highlightColor: highlightColor,
    accentColor: accentColor,
    // method: method,
  );

  /// Create a platform specific [LineStyleLayer] object.
  @override
  LineStyleLayer createLineStyleLayer({
    required String id,
    required String sourceId,
    required bool visible,
    required double minZoom,
    required double maxZoom,
    required String? sourceLayerId,
    required Expression? filter,
    required PropertyValue<double>? sortKey,
    required PropertyValue<Offset> translate,
    required PropertyValue<ReferenceSpace> translateAnchor,
    required PropertyValue<LineCap> cap,
    required PropertyValue<LineJoin> join,
    required PropertyValue<double> miterLimit,
    required PropertyValue<double> roundLimit,
    required PropertyValue<double> opacity,
    required PropertyValue<Color> color,
    required PropertyValue<double> width,
    required PropertyValue<double> gapWidth,
    required PropertyValue<double> offset,
    required PropertyValue<double> blur,
    required PropertyValue<List<double>>? dashArray,
    required PropertyValue<String>? pattern,
    required PropertyValue<Color>? gradient,
  }) => LineStyleLayerIos(
    id: id,
    sourceId: sourceId,
    visible: visible,
    minZoom: minZoom,
    maxZoom: maxZoom,
    sourceLayerId: sourceLayerId,
    filter: filter,
    sortKey: sortKey,
    translate: translate,
    translateAnchor: translateAnchor,
    join: join,
    miterLimit: miterLimit,
    roundLimit: roundLimit,
    opacity: opacity,
    color: color,
    width: width,
    gapWidth: gapWidth,
    offset: offset,
    blur: blur,
    dashArray: dashArray,
    pattern: pattern,
    gradient: gradient,
    cap: cap,
  );

  /// Create a platform specific [RasterStyleLayer] object.
  @override
  RasterStyleLayer createRasterStyleLayer({
    required String id,
    required String sourceId,
    required bool visible,
    required double minZoom,
    required double maxZoom,
    required PropertyValue<double> opacity,
    required PropertyValue<double> hueRotate,
    required PropertyValue<double> brightnessMin,
    required PropertyValue<double> brightnessMax,
    required PropertyValue<double> saturation,
    required PropertyValue<double> contrast,
    required PropertyValue<RasterResampling> resampling,
    required PropertyValue<double> fadeDuration,
  }) => RasterStyleLayerIos(
    id: id,
    sourceId: sourceId,
    visible: visible,
    minZoom: minZoom,
    maxZoom: maxZoom,
    opacity: opacity,
    hueRotate: hueRotate,
    brightnessMin: brightnessMin,
    brightnessMax: brightnessMax,
    saturation: saturation,
    contrast: contrast,
    resampling: resampling,
    fadeDuration: fadeDuration,
  );

  /// Create a platform specific [SymbolStyleLayer] object.
  @override
  SymbolStyleLayer createSymbolStyleLayer({
    required String id,
    required String sourceId,
    required bool visible,
    required double minZoom,
    required double maxZoom,
    required String? sourceLayerId,
    required Expression? filter,
    required PropertyValue<double>? sortKey,
    required PropertyValue<SymbolPlacement> placement,
    required PropertyValue<double> spacing,
    required PropertyValue<bool> avoidEdges,
    required PropertyValue<SymbolZOrder> zOrder,
    required PropertyValue<bool> iconAllowOverlap,
    required PropertyValue<SymbolOverlap> iconOverlap,
    required PropertyValue<bool> iconIgnorePlacement,
    required PropertyValue<bool> iconOptional,
    required PropertyValue<IconRotationAlignment> iconRotationAlignment,
    required PropertyValue<double> iconSize,
    required PropertyValue<IconTextFit> iconTextFit,
    required PropertyValue<EdgeInsets> iconTextFitPadding,
    required PropertyValue<String>? iconImage,
    required PropertyValue<double> iconRotate,
    required PropertyValue<EdgeInsets> iconPadding,
    required PropertyValue<bool> iconKeepUpright,
    required PropertyValue<Offset> iconOffset,
    required PropertyValue<IconAnchor> iconAnchor,
    required PropertyValue<IconPitchAlignment> iconPitchAlignment,
    required PropertyValue<TextPitchAlignment> textPitchAlignment,
    required PropertyValue<TextRotationAlignment> textRotationAlignment,
    required PropertyValue<String> textField,
    required PropertyValue<List<String>> textFont,
    required PropertyValue<double> textSize,
    required PropertyValue<double> textMaxWidth,
    required PropertyValue<double> textLineHeight,
    required PropertyValue<double> textLetterSpacing,
    required PropertyValue<TextJustify> textJustify,
    required PropertyValue<double> textRadialOffset,
    required PropertyValue<List<IconAnchor>>? textVariableAnchor,
    required PropertyValue<Map<String, Offset>>? textVariableAnchorOffset,
    required PropertyValue<TextAnchor> textAnchor,
    required PropertyValue<double> textMaxAngle,
    required PropertyValue<List<TextWritingMode>>? textWritingMode,
    required PropertyValue<double> textRotate,
    required PropertyValue<double> textPadding,
    required PropertyValue<bool> textKeepUpright,
    required PropertyValue<TextTransform> textTransform,
    required PropertyValue<Offset> textOffset,
    required PropertyValue<bool> textAllowOverlap,
    required PropertyValue<SymbolOverlap>? textOverlap,
    required PropertyValue<bool> textIgnorePlacement,
    required PropertyValue<bool> textOptional,
    required PropertyValue<double> iconOpacity,
    required PropertyValue<Color> iconColor,
    required PropertyValue<Color> iconHaloColor,
    required PropertyValue<double> iconHaloWidth,
    required PropertyValue<double> iconHaloBlur,
    required PropertyValue<Offset> iconTranslate,
    required PropertyValue<ReferenceSpace> iconTranslateAnchor,
    required PropertyValue<double> textOpacity,
    required PropertyValue<Color> textColor,
    required PropertyValue<Color> textHaloColor,
    required PropertyValue<double> textHaloWidth,
    required PropertyValue<double> textHaloBlur,
    required PropertyValue<Offset> textTranslate,
    required PropertyValue<ReferenceSpace> textTranslateAnchor,
  }) => SymbolStyleLayerIos(
    id: id,
    sourceId: sourceId,
    visible: visible,
    minZoom: minZoom,
    maxZoom: maxZoom,
    sourceLayerId: sourceLayerId,
    filter: filter,
    sortKey: sortKey,
    placement: placement,
    spacing: spacing,
    avoidEdges: avoidEdges,
    zOrder: zOrder,
    iconAllowOverlap: iconAllowOverlap,
    iconOverlap: iconOverlap,
    iconIgnorePlacement: iconIgnorePlacement,
    iconOptional: iconOptional,
    iconRotationAlignment: iconRotationAlignment,
    iconSize: iconSize,
    iconTextFit: iconTextFit,
    iconTextFitPadding: iconTextFitPadding,
    iconImage: iconImage,
    iconRotate: iconRotate,
    iconPadding: iconPadding,
    iconKeepUpright: iconKeepUpright,
    iconOffset: iconOffset,
    iconAnchor: iconAnchor,
    iconPitchAlignment: iconPitchAlignment,
    textPitchAlignment: textPitchAlignment,
    textRotationAlignment: textRotationAlignment,
    textField: textField,
    textFont: textFont,
    textSize: textSize,
    textMaxWidth: textMaxWidth,
    textLineHeight: textLineHeight,
    textLetterSpacing: textLetterSpacing,
    textJustify: textJustify,
    textRadialOffset: textRadialOffset,
    textVariableAnchor: textVariableAnchor,
    textVariableAnchorOffset: textVariableAnchorOffset,
    textAnchor: textAnchor,
    textMaxAngle: textMaxAngle,
    textWritingMode: textWritingMode,
    textRotate: textRotate,
    textPadding: textPadding,
    textKeepUpright: textKeepUpright,
    textTransform: textTransform,
    textOffset: textOffset,
    textAllowOverlap: textAllowOverlap,
    textOverlap: textOverlap,
    textIgnorePlacement: textIgnorePlacement,
    textOptional: textOptional,
    iconOpacity: iconOpacity,
    iconColor: iconColor,
    iconHaloColor: iconHaloColor,
    iconHaloWidth: iconHaloWidth,
    iconHaloBlur: iconHaloBlur,
    iconTranslate: iconTranslate,
    iconTranslateAnchor: iconTranslateAnchor,
    textOpacity: textOpacity,
    textColor: textColor,
    textHaloColor: textHaloColor,
    textHaloWidth: textHaloWidth,
    textHaloBlur: textHaloBlur,
    textTranslate: textTranslate,
    textTranslateAnchor: textTranslateAnchor,
  );
}
