#include "MapLibre/MLNMapProjection.h"
#include "MapLibre/MLNStyle.h"
#include "MapLibre/MLNSource.h"
#include "MapLibre/MLNVectorTileSource.h"
#include "MapLibre/MLNComputedShapeSource.h"
#include "MapLibre/MLNImageSource.h"
#include "MapLibre/MLNRasterTileSource.h"
#include "MapLibre/MLNRasterDEMSource.h"
#include "MapLibre/MLNBackgroundStyleLayer.h"
#include "MapLibre/MLNCircleStyleLayer.h"
#include "MapLibre/MLNFillExtrusionStyleLayer.h"
#include "MapLibre/MLNFillStyleLayer.h"
#include "MapLibre/MLNHeatmapStyleLayer.h"
#include "MapLibre/MLNHillshadeStyleLayer.h"
#include "MapLibre/MLNLineStyleLayer.h"
#include "MapLibre/MLNRasterStyleLayer.h"
#include "MapLibre/MLNSymbolStyleLayer.h"
#include "MapLibre/MLNVectorStyleLayer.h"
#include "MapLibre/MLNAttributionInfo.h"
#include "MapLibre/NSExpression+MLNAdditions.h"
#include "MapLibre/MLNOfflineStorage.h"
#include "MapLibre/MLNOfflinePack.h"
#include "MapLibre/MLNOfflineRegion.h"
#include "MapLibre/MLNTilePyramidOfflineRegion.h"
#include "MapLibre/MLNFeature.h"

/// Stub interface, so that ffigen can generate a getter for MLNFeature#identifier
/// https://github.com/dart-lang/native/issues/2492
@interface MLNFeatureWrapper : NSObject <MLNFeature>
@end