name: Feature Request
description: Suggest a Feature
title: "[FEATURE] <title>"
labels: [ "feature" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Please describe the feature you have in mind.
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Sample Use Case
      description: It is important to have at least one real-work szenario where this feature is required. There is no need to share any personal information here.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Existing Alternatives or Workarounds
      description: A clear and concise description of any alternative solutions or workarounds.
    validations:
      required: false
  - type: textarea
    id: media
    attributes:
      label: Additional Context
      description: Add or link any other resources or append media like screenshots about your feature request here.
    validations:
      required: false
