// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// ignore_for_file: type=lint

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../android/content/Context.dart' as context$_;

import 'util/DefaultStyle.dart' as defaultstyle$_;

import 'util/TileServerOptions.dart' as tileserveroptions$_;

/// from: `org.maplibre.android.MapLibre`
class MapLibre extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<MapLibre> $type;

  @jni$_.internal
  MapLibre.fromReference(
    jni$_.JReference reference,
  ) : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'org/maplibre/android/MapLibre');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $MapLibre$NullableType();
  static const type = $MapLibre$Type();
  static final _id_getInstance = _class.staticMethodId(
    r'getInstance',
    r'(Landroid/content/Context;)Lorg/maplibre/android/MapLibre;',
  );

  static final _getInstance =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public org.maplibre.android.MapLibre getInstance(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  static MapLibre getInstance(
    context$_.Context context,
  ) {
    final _$context = context.reference;
    return _getInstance(
      _class.reference.pointer,
      _id_getInstance as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).object<MapLibre>(const $MapLibre$Type());
  }

  static final _id_getInstance$1 = _class.staticMethodId(
    r'getInstance',
    r'(Landroid/content/Context;Ljava/lang/String;Lorg/maplibre/android/WellKnownTileServer;)Lorg/maplibre/android/MapLibre;',
  );

  static final _getInstance$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public org.maplibre.android.MapLibre getInstance(android.content.Context context, java.lang.String string, org.maplibre.android.WellKnownTileServer wellKnownTileServer)`
  /// The returned object must be released after use, by calling the [release] method.
  static MapLibre getInstance$1(
    context$_.Context context,
    jni$_.JString? string,
    jni$_.JObject? wellKnownTileServer,
  ) {
    final _$context = context.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$wellKnownTileServer =
        wellKnownTileServer?.reference ?? jni$_.jNullReference;
    return _getInstance$1(
      _class.reference.pointer,
      _id_getInstance$1 as jni$_.JMethodIDPtr,
      _$context.pointer,
      _$string.pointer,
      _$wellKnownTileServer.pointer,
    ).object<MapLibre>(const $MapLibre$Type());
  }

  static final _id_getApiKey = _class.staticMethodId(
    r'getApiKey',
    r'()Ljava/lang/String;',
  );

  static final _getApiKey =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.String getApiKey()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? getApiKey() {
    return _getApiKey(
      _class.reference.pointer,
      _id_getApiKey as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_setApiKey = _class.staticMethodId(
    r'setApiKey',
    r'(Ljava/lang/String;)V',
  );

  static final _setApiKey =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void setApiKey(java.lang.String string)`
  static void setApiKey(
    jni$_.JString? string,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _setApiKey(
      _class.reference.pointer,
      _id_setApiKey as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).check();
  }

  static final _id_getTileServerOptions = _class.staticMethodId(
    r'getTileServerOptions',
    r'()Lorg/maplibre/android/util/TileServerOptions;',
  );

  static final _getTileServerOptions =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public org.maplibre.android.util.TileServerOptions getTileServerOptions()`
  /// The returned object must be released after use, by calling the [release] method.
  static tileserveroptions$_.TileServerOptions? getTileServerOptions() {
    return _getTileServerOptions(
      _class.reference.pointer,
      _id_getTileServerOptions as jni$_.JMethodIDPtr,
    ).object<tileserveroptions$_.TileServerOptions?>(
      const tileserveroptions$_.$TileServerOptions$NullableType(),
    );
  }

  static final _id_getPredefinedStyles = _class.staticMethodId(
    r'getPredefinedStyles',
    r'()[Lorg/maplibre/android/util/DefaultStyle;',
  );

  static final _getPredefinedStyles =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public org.maplibre.android.util.DefaultStyle[] getPredefinedStyles()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<defaultstyle$_.DefaultStyle?>? getPredefinedStyles() {
    return _getPredefinedStyles(
      _class.reference.pointer,
      _id_getPredefinedStyles as jni$_.JMethodIDPtr,
    ).object<jni$_.JArray<defaultstyle$_.DefaultStyle?>?>(
      const jni$_.JArrayNullableType<defaultstyle$_.DefaultStyle?>(
        defaultstyle$_.$DefaultStyle$NullableType(),
      ),
    );
  }

  static final _id_getPredefinedStyle = _class.staticMethodId(
    r'getPredefinedStyle',
    r'(Ljava/lang/String;)Lorg/maplibre/android/util/DefaultStyle;',
  );

  static final _getPredefinedStyle =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public org.maplibre.android.util.DefaultStyle getPredefinedStyle(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  static defaultstyle$_.DefaultStyle? getPredefinedStyle(
    jni$_.JString? string,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getPredefinedStyle(
      _class.reference.pointer,
      _id_getPredefinedStyle as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<defaultstyle$_.DefaultStyle?>(
      const defaultstyle$_.$DefaultStyle$NullableType(),
    );
  }

  static final _id_getApplicationContext = _class.staticMethodId(
    r'getApplicationContext',
    r'()Landroid/content/Context;',
  );

  static final _getApplicationContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public android.content.Context getApplicationContext()`
  /// The returned object must be released after use, by calling the [release] method.
  static context$_.Context getApplicationContext() {
    return _getApplicationContext(
      _class.reference.pointer,
      _id_getApplicationContext as jni$_.JMethodIDPtr,
    ).object<context$_.Context>(const context$_.$Context$Type());
  }

  static final _id_setConnected = _class.staticMethodId(
    r'setConnected',
    r'(Ljava/lang/Boolean;)V',
  );

  static final _setConnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void setConnected(java.lang.Boolean boolean)`
  static void setConnected(
    jni$_.JBoolean? boolean,
  ) {
    final _$boolean = boolean?.reference ?? jni$_.jNullReference;
    _setConnected(
      _class.reference.pointer,
      _id_setConnected as jni$_.JMethodIDPtr,
      _$boolean.pointer,
    ).check();
  }

  static final _id_isConnected = _class.staticMethodId(
    r'isConnected',
    r'()Ljava/lang/Boolean;',
  );

  static final _isConnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.Boolean isConnected()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JBoolean? isConnected() {
    return _isConnected(
      _class.reference.pointer,
      _id_isConnected as jni$_.JMethodIDPtr,
    ).object<jni$_.JBoolean?>(const jni$_.JBooleanNullableType());
  }

  static final _id_getModuleProvider = _class.staticMethodId(
    r'getModuleProvider',
    r'()Lorg/maplibre/android/ModuleProvider;',
  );

  static final _getModuleProvider =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public org.maplibre.android.ModuleProvider getModuleProvider()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JObject getModuleProvider() {
    return _getModuleProvider(
      _class.reference.pointer,
      _id_getModuleProvider as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_setModuleProvider = _class.staticMethodId(
    r'setModuleProvider',
    r'(Lorg/maplibre/android/ModuleProvider;)V',
  );

  static final _setModuleProvider =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void setModuleProvider(org.maplibre.android.ModuleProvider moduleProvider)`
  static void setModuleProvider(
    jni$_.JObject? moduleProvider,
  ) {
    final _$moduleProvider = moduleProvider?.reference ?? jni$_.jNullReference;
    _setModuleProvider(
      _class.reference.pointer,
      _id_setModuleProvider as jni$_.JMethodIDPtr,
      _$moduleProvider.pointer,
    ).check();
  }

  static final _id_throwIfApiKeyInvalid = _class.staticMethodId(
    r'throwIfApiKeyInvalid',
    r'(Ljava/lang/String;)V',
  );

  static final _throwIfApiKeyInvalid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void throwIfApiKeyInvalid(java.lang.String string)`
  static void throwIfApiKeyInvalid(
    jni$_.JString? string,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _throwIfApiKeyInvalid(
      _class.reference.pointer,
      _id_throwIfApiKeyInvalid as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).check();
  }

  static final _id_hasInstance = _class.staticMethodId(
    r'hasInstance',
    r'()Z',
  );

  static final _hasInstance =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public boolean hasInstance()`
  static bool hasInstance() {
    return _hasInstance(
      _class.reference.pointer,
      _id_hasInstance as jni$_.JMethodIDPtr,
    ).boolean;
  }
}

final class $MapLibre$NullableType extends jni$_.JObjType<MapLibre?> {
  @jni$_.internal
  const $MapLibre$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lorg/maplibre/android/MapLibre;';

  @jni$_.internal
  @core$_.override
  MapLibre? fromReference(jni$_.JReference reference) => reference.isNull
      ? null
      : MapLibre.fromReference(
          reference,
        );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<MapLibre?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MapLibre$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MapLibre$NullableType) &&
        other is $MapLibre$NullableType;
  }
}

final class $MapLibre$Type extends jni$_.JObjType<MapLibre> {
  @jni$_.internal
  const $MapLibre$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lorg/maplibre/android/MapLibre;';

  @jni$_.internal
  @core$_.override
  MapLibre fromReference(jni$_.JReference reference) => MapLibre.fromReference(
    reference,
  );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<MapLibre?> get nullableType => const $MapLibre$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MapLibre$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MapLibre$Type) && other is $MapLibre$Type;
  }
}
