name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

# Ensure that new pushes/updates cancel running jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-test-web:
    name: "[Web] Integration tests"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: examples
    strategy:
      fail-fast: false
      matrix:
        sdk: ['3.38.10', '']
    env:
      CI: true
      CHROME_FLAGS: --no-sandbox --disable-dev-shm-usage
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Setup Flutter SDK"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.sdk }}
          cache: true
      - name: "Setup Chrome"
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
      - name: "Setup ChromeDriver"
        id: setup-chromedriver
        uses: nanasess/setup-chromedriver@v2
      - name: "Export Chrome paths"
        run: |
          echo "CHROME_EXECUTABLE=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV
      - name: "Enable Flutter web support"
        run: flutter config --enable-web
      - name: "Install dependencies"
        run: flutter pub get
      - name: "Start ChromeDriver"
        run: |
          "$CHROMEDRIVER_PATH" --port=4444 &
          sleep 2
      - name: "Run web integration tests"
        run: xvfb-run -a flutter drive --driver=test_driver/integration_test.dart --target=integration_test/main.dart -d chrome --timeout 600 --dart-define=FLUTTER_WEB_USE_SKIA=true
