name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

# Ensure that new pushes/updates cancel running jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-test-ios:
    name: "[iOS] Integration tests"
    runs-on: macOS-latest
    defaults: { run: { working-directory: examples } }
    strategy:
      fail-fast: false
      matrix:
        os_version: [ '18.6', '26.2' ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with: { cache: true }
      - name: Install dependencies
        run: flutter pub get
      - name: Enable Swift Package Manager
        run: flutter config --enable-swift-package-manager
      - name: Start iOS simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 16 Pro'
          os_version: ${{ matrix.os_version }}
      - name: Wait for simulator
        run: xcrun simctl bootstatus booted -b
      - name: Run integration tests
        run: flutter test integration_test/main.dart --timeout=1800s -r expanded --coverage --coverage-package maplibre.*
      - name: "Run Codecov"
        uses: codecov/codecov-action@v5
        if: ${{ matrix.os_version == '26.2' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  integration-test-web:
    name: "[Web] Integration tests"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: examples
    strategy:
      fail-fast: false
      matrix:
        sdk: ['3.38.10', '']
    env:
      CI: true
      CHROME_FLAGS: --no-sandbox
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Setup Flutter SDK"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.sdk }}
          cache: true
      - name: "Setup Chrome"
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
      - name: "Setup ChromeDriver"
        id: setup-chromedriver
        uses: nanasess/setup-chromedriver@v2
      - name: "Export Chrome paths"
        run: |
          echo "CHROME_EXECUTABLE=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV
      - name: "Enable Flutter web support"
        run: flutter config --enable-web
      - name: "Install dependencies"
        run: flutter pub get
      - name: "Start ChromeDriver"
        run: |
          "$CHROMEDRIVER_PATH" --port=4444 &
          sleep 2
      - name: "Run web integration tests"
        run: xvfb-run -a flutter drive --driver=test_driver/integration_test.dart --target=integration_test/main.dart -d chrome --timeout 120 --dart-define=FLUTTER_WEB_USE_SKIA=true
